apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
    tier: jaeger
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
      tier: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        tier: jaeger
        version: v1
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: jaeger
        image: {{ .Values.jaeger.server.image.name }}:{{ .Values.jaeger.server.image.tag }} # jaegertracing/all-in-one:1.31
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        ports:
        - containerPort: 5775
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 5778
        - containerPort: 14250
        - containerPort: 14268
        - containerPort: 14269
        - containerPort: 16686
        - containerPort: 9411
        resources:
          requests:
            cpu: {{ .Values.jaeger.server.requests.cpu }} # 200m
            memory: {{ .Values.jaeger.server.requests.memory }} # 180Mi
          limits:
            cpu: {{ .Values.jaeger.server.limits.cpu }} # 300m
            memory: {{ .Values.jaeger.server.limits.memory }} # 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: jaeger
    tier: jaeger
spec:
  type: {{ .Values.jaeger.service.type }} # ClusterIP
  selector:
    tier: jaeger
  ports:
  - name: "5775"
    port: {{ .Values.jaeger.service.p5775.port }} # 5775
    targetPort: {{ .Values.jaeger.service.p5775.targetPort }} # 5775
    protocol: {{ .Values.jaeger.service.p5775.protocol }} # UDP
  - name: "6831"
    port: {{ .Values.jaeger.service.p6831.port }} # 6831
    targetPort: {{ .Values.jaeger.service.p6831.targetPort }} # 6831
    protocol: {{ .Values.jaeger.service.p6831.protocol }} # UDP
  - name: "6832"
    port: {{ .Values.jaeger.service.p6832.port }} # 6832
    targetPort: {{ .Values.jaeger.service.p6832.targetPort }} # 6832
    protocol: {{ .Values.jaeger.service.p6832.protocol }} # UDP
  - name: "5778"
    port: {{ .Values.jaeger.service.p5778.port }} # 5778
    targetPort: {{ .Values.jaeger.service.p5778.targetPort }} # 5778
  - name: "14250"
    port: {{ .Values.jaeger.service.p14250.port }} # 14250
    targetPort: {{ .Values.jaeger.service.p14250.targetPort }} # 14250
  - name: "14268"
    port: {{ .Values.jaeger.service.p14268.port }} # 14268
    targetPort: {{ .Values.jaeger.service.p14268.targetPort }} # 14268
  - name: "14269"
    port: {{ .Values.jaeger.service.p14269.port }} # 14269
    targetPort: {{ .Values.jaeger.service.p14269.targetPort }} # 14269
  - name: "9411"
    port: {{ .Values.jaeger.service.p9411.port }} # 9411
    targetPort: {{ .Values.jaeger.service.p9411.targetPort }} # 9411
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-frontend
  labels:
    app: jaeger-frontend
    tier: jaeger
spec:
  type: {{ .Values.jaegerfrontend.service.type }} # NodePort
  selector:
    tier: jaeger
  ports:
  - name: "16686"
    port: {{ .Values.jaegerfrontend.service.p16686.port }} # 16686
    targetPort: {{ .Values.jaegerfrontend.service.p16686.targetPort }} # 16686
