# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
    tier: loadgenerator
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
      tier: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
        tier: loadgenerator
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
          if test $STATUSCODE -ne 200; then
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              exit 1
          fi
        name: frontend-check
        image: {{ .Values.loadgenerator.frontendcheck.image.name }}:{{ .Values.loadgenerator.frontendcheck.image.tag }} # busybox:latest
        env:
        - name: FRONTEND_ADDR
          value: {{ .Values.loadgenerator.frontendcheck.env.FRONTEND_ADDR }} # "frontend:80"
      containers:
      - name: main
        image: {{ .Values.loadgenerator.main.image.name }}:{{ .Values.loadgenerator.main.image.tag }} # loadgenerator
        env:
        - name: FRONTEND_ADDR
          value: {{ .Values.loadgenerator.main.env.FRONTEND_ADDR }} # "frontend:80"
        - name: USERS
          value: {{ .Values.loadgenerator.main.env.USERS }} # "10"
        resources:
          requests:
            cpu: {{ .Values.loadgenerator.main.requests.cpu }} # 300m
            memory: {{ .Values.loadgenerator.main.requests.memory }} # 256Mi
          limits:
            cpu: {{ .Values.loadgenerator.main.limits.cpu }} # 500m
            memory: {{ .Values.loadgenerator.main.limits.memory }} # 512Mi
