# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    framework: python
    app: recommendationservice
    tier: recommendationservice
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/component: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
      tier: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
        tier: recommendationservice
        version: v1
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: {{ .Values.recommendationservice.server.image.name }}:{{ .Values.recommendationservice.server.image.tag }}
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: {{ .Values.recommendationservice.server.env.PRODUCT_CATALOG_SERVICE_ADDR }} # "productcatalogservice:3550"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: {{ .Values.recommendationservice.server.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT }} # "http://otelcollector:4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: {{ .Values.recommendationservice.server.env.OTEL_RESOURCE_ATTRIBUTES }} # "service.name=productcatalogservice,service.version=1.0.0"
        resources:
          requests:
            cpu: {{ .Values.recommendationservice.server.requests.cpu }} # 100m
            memory: {{ .Values.recommendationservice.server.requests.memory }} # 220Mi
          limits:
            cpu: {{ .Values.recommendationservice.server.limits.cpu }} # 200m
            memory: {{ .Values.recommendationservice.server.limits.memory }} # 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
    tier: recommendationservice
spec:
  type: {{ .Values.recommendationservice.service.type }} # ClusterIP
  selector:
    tier: recommendationservice
  ports:
  - name: grpc
    port: {{ .Values.recommendationservice.service.grpc.port }} # 8080
    targetPort: {{ .Values.recommendationservice.service.grpc.targetPort }} # 8080
