adservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/adservice # gcr.io/google-samples/microservices-demo/adservice
      tag: v0.1.0
    requests:
      cpu: 400m
      memory: 360Mi
    limits:
      cpu: 600m
      memory: 600Mi
    env:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=adservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 9555 ## External Port for LoadBalancer/NodePort
      targetPort: 9555

cartservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/cartservice # gcr.io/google-samples/microservices-demo/cartservice
      tag: v0.1.0
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi
    env:
      REDIS_ADDR: "redis-cart:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otelcollector:4317" # NOT OTEL_EXPORTER_OTLP_TRACES_ENDPOINT !?
      OTEL_RESOURCE_ATTRIBUTES: "service.name=cartservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 7070 ## External Port for LoadBalancer/NodePort
      targetPort: 7070

checkoutservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/checkoutservice # gcr.io/google-samples/microservices-demo/checkoutservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      PAYMENT_SERVICE_ADDR: "paymentservice:50051"
      EMAIL_SERVICE_ADDR: "emailservice:5000"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=checkoutservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 5050 ## External Port for LoadBalancer/NodePort
      targetPort: 5050

currencyservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/currencyservice # gcr.io/google-samples/microservices-demo/currencyservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
    env:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=currencyservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 7000 ## External Port for LoadBalancer/NodePort
      targetPort: 7000


emailservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/emailservice # gcr.io/google-samples/microservices-demo/emailservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
    env:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=emailservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 5000 ## External Port for LoadBalancer/NodePort
      targetPort: 8080

frontend:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/frontend # gcr.io/google-samples/microservices-demo/frontend
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"
      RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
      AD_SERVICE_ADDR: "adservice:9555"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=frontend,service.version=1.0.0"
      # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
      # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp
      ENV_PLATFORM: "local"
      CYMBAL_BRANDING: "'false'" # disabled
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    http:
      port: 80 ## External Port for LoadBalancer/NodePort
      targetPort: 8080

frontendexternal:
  service:
    type: NodePort # ClusterIP, NodePort, LoadBalancer
    http:
      port: 80 ## External Port for LoadBalancer/NodePort
      targetPort: 8080

jaeger:
  replicas: 1
  server:
    image:
      name: jaegertracing/all-in-one
      tag: latest # 1.31
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    p5775:
      port: 5775
      targetPort: 5775
      protocol: UDP
    p6831:
      port: 6831
      targetPort: 6831
      protocol: UDP
    p6832:
      port: 6832
      targetPort: 6832
      protocol: UDP
    p5778:
      port: 5778
      targetPort: 5778
    p14250:
      port: 14250
      targetPort: 14250
    p14268:
      port: 14268
      targetPort: 14268
    p14269:
      port: 14269
      targetPort: 14269
    p9411:
      port: 9411
      targetPort: 9411

jaegerfrontend:
  service:
    type: NodePort # ClusterIP, NodePort, LoadBalancer
    p16686:
      port: 16686
      targetPort: 16686

loadgenerator:
  replicas: 1
  frontendcheck:
    image:
      name: busybox
      tag: latest
    env:
      FRONTEND_ADDR: "frontend:80"
  main:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/loadgenerator # gcr.io/google-samples/microservices-demo/loadgenerator
      tag: v0.1.0
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
    env:
      FRONTEND_ADDR: "frontend:80"
      USERS: "'10'"

otelcollector:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/otelcollector
      tag: v0.1.0
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi
    env:
      APPD_ENDPOINT: "https://pdx-sls-agent-api.saas.appdynamics.com/"
      APPD_KEY: ""
      APPD_CONTROLLER_ACCOUNT: ""
      APPD_CONTROLLER_HOST: ""
      APPD_CONTROLLER_PORT: "'443'"
      SERVICE_NAMESPACE: ""
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    p1888:
      port: 1888
      targetPort: 1888
    p8888:
      port: 8888
      targetPort: 8888
    p8889:
      port: 8889
      targetPort: 8889
    p13133:
      port: 13133
      targetPort: 13133
    p4317:
      port: 4317
      targetPort: 4317
    p55670:
      port: 55670
      targetPort: 55670

paymentservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/paymentservice # gcr.io/google-samples/microservices-demo/paymentservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
    env:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=paymentservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 50051 ## External Port for LoadBalancer/NodePort
      targetPort: 50051

paymentservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/paymentservice # gcr.io/google-samples/microservices-demo/paymentservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
    env:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=paymentservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 50051 ## External Port for LoadBalancer/NodePort
      targetPort: 50051

productcatalogservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/productcatalogservice # gcr.io/google-samples/microservices-demo/productcatalogservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
    env:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=productcatalogservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 3550 ## External Port for LoadBalancer/NodePort
      targetPort: 3550

recommendationservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/recommendationservice # gcr.io/google-samples/microservices-demo/recommendationservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=recommendationservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 8080 ## External Port for LoadBalancer/NodePort
      targetPort: 8080

redis:
  replicas: 1
  server:
    image:
      name: redis
      tag: alpine
    requests:
      cpu: 70m
      memory: 200Mi
    limits:
      cpu: 125m
      memory: 256Mi
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    redis:
      port: 6379 ## External Port for LoadBalancer/NodePort
      targetPort: 6379

shippingservice:
  replicas: 1
  server:
    image:
      name: public.ecr.aws/j8r8c0y6/otel-online-boutique/shippingservice # gcr.io/google-samples/microservices-demo/shippingservice
      tag: v0.1.0
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://otelcollector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=shippingservice,service.version=1.0.0"
  service:
    type: ClusterIP # ClusterIP, NodePort, LoadBalancer
    grpc:
      port: 50051 ## External Port for LoadBalancer/NodePort
      targetPort: 50051
